{% set name = "metget" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/waterinstitute/MetGet/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1ccd2ee1f6c682b043cdfedde9af785265af0ca77797bea7e714cdf680671a26

build:
  entry_points:
    - metget = metget:metget_client_cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - requests
    - yaspin
    - prettytable

test:
  imports:
    - metget
  commands:
    - pip check
    - metget --help
    - metget --version
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: A client package for interaction with a MetGet server instance
  home: https://github.com/waterinstitute/metget
  dev_url: https://github.com/waterinstitute/metget
  license: MIT
  license_family: MIT
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - zcobell
